steps:
  - name: "gcr.io/cloud-builders/docker"
    id: build Step
    args: ["build", "-t", "gcr.io/ringed-robot-349322/my-nginx:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    id: push Step
    args: ["push", "gcr.io/ringed-robot-349322/my-nginx:latest"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: deploy Step
    args:
      - apply
      - --filename=gs://ring-robot-nginx-deployment/deployment.yaml
      - --namespace=default
      - --location=us-central1-c
      - --cluster=cluster-2
